Minor fixes

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -27,7 +27,7 @@ runs:
       id: validate-max-required-client-version-error-message
       if: "failure() && steps.validate-max-required-client-version.outcome == 'failure'"
       shell: bash
-      run: 'echo "::error ::Invalid max-required-client-version'
+      run: 'echo "::error ::Invalid max-required-client-version passed to ${{ github.action_repository }}";exit 1'
     
     - name: 'Extract client compatibility version from dmb'
       id: fetch-required-client-version
@@ -49,6 +49,6 @@ runs:
     
     - name: 'Version validation error message'
       id: check-required-client-version-error
-      if: "failure() && steps.validate-max-required-client-version.outcome == 'failure'"
+      if: "failure() && steps.check-required-client-version.outcome == 'failure'"
       shell: bash
       run: 'echo "::error file=${{ inputs.dmb-location }},line=2,endline=2::byond world ${{ inputs.dmb-location }} requires version ${{ steps.fetch-required-client-version.outputs.required-client-version }} which is higher than the allowed max required version of ${{ inputs.max-required-client-version }}.";exit 1'
