error handling clean up.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,5 +1,5 @@
 name: 'Byond Client Compatibility Check'
-description: "Github action to confirm that the required client version of byond world (.dmb) isn't higher than expected. "
+description: "Github action to confirm that the required client version of byond world (.dmb) isn't higher than expected."
 
 inputs:
   dmb-location: 
@@ -23,13 +23,32 @@ runs:
       run: '(( ${{ inputs.max-required-client-version }} ))'
       if: 'inputs.max-required-client-version != 9999'
     
+    - name: 'Input validation error message'
+      id: validate-max-required-client-version-error-message
+      if: "failure() && steps.validate-max-required-client-version.conclusion == 'failure'"
+      shell: bash
+      run: 'echo "::error ::Invalid max-required-client-version'
+    
     - name: 'Extract client compatibility version from dmb'
       id: fetch-required-client-version
       shell: bash
-      run: 'echo "required-client-version=$( $(( head -n2 ${{ inputs.dmb-location }} | tail -n1 | cut -d " " -f 4 )) )" >> $GITHUB_OUTPUT'
+      run: 'echo "required-client-version=$(( $( head -n2 ${{ inputs.dmb-location }} | tail -n1 | cut -d " " -f 4 ) ))" >> $GITHUB_OUTPUT'
     
+    - name: '.dmb parse error check'
+      id: dmb-parse-error-check
+      if: "(failure() && steps.fetch-required-client-version.conclusion == 'failure') || (success && (steps.fetch-required-client-version.outputs.required-client-version == null || steps.fetch-required-client-version.outputs.required-client-version == ''))"
+      shell: bash
+      run: 'echo "::error file=${{ inputs.dmb-location }},line=1,endline=2::Error parsing dmb for required client version";exit 1'
+      
     - name: 'Check required client version is not higher then allowed max.'
       id: check-required-client-version
       shell: bash
-      run: (( $(( ${{ steps.fetch-required-client-version.outputs.required-client-version }} )) <= $(( ${{ inputs.max-required-client-version }} )) ))
+      #this still uses bash instead of an if: and echo purely so that it can't support floats.
+      run: (( ${{ steps.fetch-required-client-version.outputs.required-client-version }} <= ${{ inputs.max-required-client-version }} ))
       if: 'inputs.max-required-client-version != 9999'
+    
+    - name: 'Version validation error message'
+      id: check-required-client-version-error
+      if: "failure() && steps.validate-max-required-client-version.conclusion == 'failure'"
+      shell: bash
+      run: 'echo "::error file=${{ inputs.dmb-location }},line=2,endline=2::byond world ${{ inputs.dmb-location }} requires version ${{ steps.fetch-required-client-version.outputs.required-client-version }} which is higher than the allowed max required version of ${{ inputs.max-required-client-version }}.";exit 1'
